# Generated by Django 3.2.9 on 2023-01-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0002_addproduct_salesinvoice_salesproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='product_number',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='barcode_no',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
