# Generated by Django 3.2.9 on 2023-01-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0003_auto_20230118_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=300, null=True),
        ),
    ]
