# Generated by Django 3.2.9 on 2023-01-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0005_auto_20230118_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='quantity',
            new_name='product_quantity',
        ),
        migrations.AddField(
            model_name='addproduct',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=300, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=300, null=True),
        ),
        migrations.AlterField(
            model_name='generateproduct',
            name='barcode_no',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
