# Generated by Django 4.1.5 on 2023-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0007_addproduct_generate_addproduct_q_measurements_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinvoice',
            old_name='total_balance',
            new_name='amount_received',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='q_measurements',
            field=models.CharField(choices=[('ml', 'ml'), ('L', 'L'), ('g', 'g'), ('Kg', 'Kg'), ('Pieces', 'Pieces')], max_length=255, null=True),
        ),
    ]
