# Generated by Django 4.1.5 on 2023-01-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0008_rename_total_balance_salesinvoice_amount_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='tq_units',
            field=models.CharField(choices=[('L', 'L'), ('Kg', 'Kg'), ('Pcs', 'Pcs')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='q_measurements',
            field=models.CharField(choices=[('ml', 'ml'), ('L', 'L'), ('g', 'g'), ('Kg', 'Kg'), ('Pcs', 'Pcs')], max_length=255, null=True),
        ),
    ]
