# Generated by Django 4.1.5 on 2023-01-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0009_addproduct_tq_units_alter_addproduct_q_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='out_of_stock',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
