# Generated by Django 4.1.5 on 2023-01-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0010_addproduct_out_of_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='sold',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='sold_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=300, null=True),
        ),
    ]
