# Generated by Django 4.1.5 on 2023-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_app', '0012_salesinvoice_savings_salesinvoice_total_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesproduct',
            name='enter_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='q_measurements',
            field=models.CharField(choices=[('ml', 'ml'), ('L', 'L'), ('g', 'g'), ('Kg', 'Kg'), ('Pcs', 'Pcs')], max_length=255, null=True),
        ),
    ]
